version: '3.1'

services: 
  mysql:
    image: mysql:5.7
    container_name: dvora-mysql-container
    environment: 
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'dvora'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_HOST: '%'
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes: 
      - ./dvoradata:/app/dvora_main/data
    networks: 
      - dvora-network
      
  dvora:
    build: 
      dockerfile: ./dvora.dockerfile
      context: .
    restart: on-failure
    ports:
      - "3000:3000"
    entrypoint: ["./wait-for-it.sh", "-t", "30", "mysql:3306", "--", "yarn", "dev"]
    volumes:
      - .:/home/jpbaptista/projects/dvora
    networks: 
      - dvora-network
    depends_on: 
      - "mysql"
    
networks:
  dvora-network:
    driver: bridge 